OHRI-1983: handled the (Uncaught TypeError: t.forEach is not a functi… (#148)
* OHRI-1983: handled the (Uncaught TypeError: t.forEach is not a function) pop up error

* update to check wether values is an array